version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
            - node_modules_data:/var/www/html/node_modules
            - vendor_data:/var/www/html/vendor
        ports:
            - "8000:8000"
        depends_on:
            - db
        environment:
            - DB_HOST="db"
            - DB_DATABASE="login"
            - DB_USERNAME="root"
            - DB_PASSWORD=""
        command: >
            sh -c "php artisan migrate --force &&
                   php artisan db:seed --force &&
                   npm run dev & php-fpm"

    db:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: "login"
            MYSQL_USER: "root"
            MYSQL_PASSWORD: ""
            MYSQL_ROOT_PASSWORD: ""
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3306:3306"

volumes:
    db_data:
    node_modules_data:
    vendor_data:
